allzero_samples_are_invalid: false
autoregressive_inputs:
- streamflow_shift1
batch_size: 256
cache:
  enabled: false
clip_gradient_norm: 1
commit_hash: ed2dfd3
dataset: multimet
detect_anomaly: false
device: cpu
dynamic_inputs:
- hres_temperature_2m
- hres_total_precipitation
- imerg_precipitation
- cpc_precipitation
dynamics_data_dir: /usr/local/google/home/kruparell/Caravans_MultiMet
dynamics_embedding:
  type: fc
  hiddens:
  - 20
  activation:
  - linear
  dropout: 0.0
epochs: 5
experiment_name: arlstm-local-example
forecast_inputs: {}
head: regression
hidden_size: 16
hindcast_inputs:
  hres:
  - hres_temperature_2m
  - hres_total_precipitation
  imerg:
  - imerg_precipitation
  cpc:
  - cpc_precipitation
img_log_dir: 
  /usr/local/google/home/kruparell/flood-forecasting/tutorial/model-runs/arlstm-local-example_1707_144041/img_log
initial_forget_bias: 3
initial_learning_rate: 0.01
lead_time: 7
learning_rate_drop_factor: 0.5
learning_rate_epochs_drop: 2
learning_rate_strategy: StepLR
load_as_csv: false
log_loss_every_nth_update: 10
log_n_figures: 0
logging_level: INFO
loss: MSE
max_updates_per_epoch: 100
metrics:
- NSE
model: arlstm
num_workers: 0
number_of_basins: 5
optimizer: Adam
output_activation: linear
output_dropout: 0.0
package_version: 1.12.0
predict_last_n: 1
print_warnings_once: false
run_dir: 
  /usr/local/google/home/kruparell/flood-forecasting/tutorial/model-runs/arlstm-local-example_1707_144041
seed: 42
seq_length: 365
static_attributes:
- area
- aridity_ERA5_LAND
- frac_snow
- p_mean
- pet_mean_ERA5_LAND
statics_data_dir: 
  /usr/local/google/home/kruparell/flood-forecasting/tutorial/Caravan-nc
statics_embedding:
  type: fc
  hiddens:
  - 20
  activation:
  - linear
  dropout: 0.0
target_noise_std: 0.005
target_variables:
- streamflow
targets_data_dir: 
  /usr/local/google/home/kruparell/flood-forecasting/tutorial/Caravan-nc
test_basin_file: 
  /usr/local/google/home/kruparell/flood-forecasting/tutorial/basin-lists/8-basin-test.txt
test_end_date: 31/12/2012
test_start_date: 01/01/2011
tester_sample_reduction: median
tester_skip_obs_all_nan: true
timestep_counter: true
train_basin_file: 
  /usr/local/google/home/kruparell/flood-forecasting/tutorial/basin-lists/5-basin-train.txt
train_dir: 
  /usr/local/google/home/kruparell/flood-forecasting/tutorial/model-runs/arlstm-local-example_1707_144041/train_data
train_end_date: 31/12/2010
train_start_date: 01/01/2000
union_mapping:
  cpc_precipitation: era5land_total_precipitation
  imerg_precipitation: era5land_total_precipitation
  hres_temperature_2m: era5land_temperature_2m
  hres_total_precipitation: era5land_total_precipitation
validate_every: 1
validate_n_random_basins: -1
validation_basin_file: 
  /usr/local/google/home/kruparell/flood-forecasting/tutorial/basin-lists/5-basin-train.txt
validation_end_date: 31/12/2012
validation_start_date: 01/01/2011
weight_init_opts:
- lstm-ih-xavier
- lstm-hh-orthogonal
- fc-xavier
